In [1]:
import numpy as np

In [2]:
a=np.array([1,4,7,9])
print(a)

[1 4 7 9]


In [3]:
b=np.ones((2,3),dtype=float)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]


In [4]:
c=np.arange(1,16).reshape(3,5)
print(c)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [8]:
d = c.flatten()

In [9]:
print(d)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
